/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TesteVocalExecutarRouteImport } from './routes/teste-vocal.executar'
import { Route as PalcoProjectIdRouteImport } from './routes/palco.$projectId'
import { Route as DiarioConcluidoRouteImport } from './routes/diario.concluido'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppTesteVocalIndexRouteImport } from './routes/_app.teste-vocal.index'
import { Route as AppSaudeIndexRouteImport } from './routes/_app.saude.index'
import { Route as AppRepertorioIndexRouteImport } from './routes/_app.repertorio.index'
import { Route as AppDiarioIndexRouteImport } from './routes/_app.diario.index'
import { Route as RepertorioImprimirProjectIdRouteImport } from './routes/repertorio.imprimir.$projectId'
import { Route as DiarioExercicioExerciseIdRouteImport } from './routes/diario.exercicio.$exerciseId'
import { Route as AppSaudeTomRouteImport } from './routes/_app.saude.tom'
import { Route as AppSaudeWarmupIdRouteImport } from './routes/_app.saude.$warmupId'
import { Route as AppRepertorioProjectIdRouteImport } from './routes/_app.repertorio.$projectId'
import { Route as AppDiarioEvolucaoRouteImport } from './routes/_app.diario.evolucao'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TesteVocalExecutarRoute = TesteVocalExecutarRouteImport.update({
  id: '/teste-vocal/executar',
  path: '/teste-vocal/executar',
  getParentRoute: () => rootRouteImport,
} as any)
const PalcoProjectIdRoute = PalcoProjectIdRouteImport.update({
  id: '/palco/$projectId',
  path: '/palco/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const DiarioConcluidoRoute = DiarioConcluidoRouteImport.update({
  id: '/diario/concluido',
  path: '/diario/concluido',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppTesteVocalIndexRoute = AppTesteVocalIndexRouteImport.update({
  id: '/teste-vocal/',
  path: '/teste-vocal/',
  getParentRoute: () => AppRoute,
} as any)
const AppSaudeIndexRoute = AppSaudeIndexRouteImport.update({
  id: '/saude/',
  path: '/saude/',
  getParentRoute: () => AppRoute,
} as any)
const AppRepertorioIndexRoute = AppRepertorioIndexRouteImport.update({
  id: '/repertorio/',
  path: '/repertorio/',
  getParentRoute: () => AppRoute,
} as any)
const AppDiarioIndexRoute = AppDiarioIndexRouteImport.update({
  id: '/diario/',
  path: '/diario/',
  getParentRoute: () => AppRoute,
} as any)
const RepertorioImprimirProjectIdRoute =
  RepertorioImprimirProjectIdRouteImport.update({
    id: '/repertorio/imprimir/$projectId',
    path: '/repertorio/imprimir/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DiarioExercicioExerciseIdRoute =
  DiarioExercicioExerciseIdRouteImport.update({
    id: '/diario/exercicio/$exerciseId',
    path: '/diario/exercicio/$exerciseId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppSaudeTomRoute = AppSaudeTomRouteImport.update({
  id: '/saude/tom',
  path: '/saude/tom',
  getParentRoute: () => AppRoute,
} as any)
const AppSaudeWarmupIdRoute = AppSaudeWarmupIdRouteImport.update({
  id: '/saude/$warmupId',
  path: '/saude/$warmupId',
  getParentRoute: () => AppRoute,
} as any)
const AppRepertorioProjectIdRoute = AppRepertorioProjectIdRouteImport.update({
  id: '/repertorio/$projectId',
  path: '/repertorio/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppDiarioEvolucaoRoute = AppDiarioEvolucaoRouteImport.update({
  id: '/diario/evolucao',
  path: '/diario/evolucao',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof AppHomeRoute
  '/diario/concluido': typeof DiarioConcluidoRoute
  '/palco/$projectId': typeof PalcoProjectIdRoute
  '/teste-vocal/executar': typeof TesteVocalExecutarRoute
  '/diario/evolucao': typeof AppDiarioEvolucaoRoute
  '/repertorio/$projectId': typeof AppRepertorioProjectIdRoute
  '/saude/$warmupId': typeof AppSaudeWarmupIdRoute
  '/saude/tom': typeof AppSaudeTomRoute
  '/diario/exercicio/$exerciseId': typeof DiarioExercicioExerciseIdRoute
  '/repertorio/imprimir/$projectId': typeof RepertorioImprimirProjectIdRoute
  '/diario/': typeof AppDiarioIndexRoute
  '/repertorio/': typeof AppRepertorioIndexRoute
  '/saude/': typeof AppSaudeIndexRoute
  '/teste-vocal/': typeof AppTesteVocalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof AppHomeRoute
  '/diario/concluido': typeof DiarioConcluidoRoute
  '/palco/$projectId': typeof PalcoProjectIdRoute
  '/teste-vocal/executar': typeof TesteVocalExecutarRoute
  '/diario/evolucao': typeof AppDiarioEvolucaoRoute
  '/repertorio/$projectId': typeof AppRepertorioProjectIdRoute
  '/saude/$warmupId': typeof AppSaudeWarmupIdRoute
  '/saude/tom': typeof AppSaudeTomRoute
  '/diario/exercicio/$exerciseId': typeof DiarioExercicioExerciseIdRoute
  '/repertorio/imprimir/$projectId': typeof RepertorioImprimirProjectIdRoute
  '/diario': typeof AppDiarioIndexRoute
  '/repertorio': typeof AppRepertorioIndexRoute
  '/saude': typeof AppSaudeIndexRoute
  '/teste-vocal': typeof AppTesteVocalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/home': typeof AppHomeRoute
  '/diario/concluido': typeof DiarioConcluidoRoute
  '/palco/$projectId': typeof PalcoProjectIdRoute
  '/teste-vocal/executar': typeof TesteVocalExecutarRoute
  '/_app/diario/evolucao': typeof AppDiarioEvolucaoRoute
  '/_app/repertorio/$projectId': typeof AppRepertorioProjectIdRoute
  '/_app/saude/$warmupId': typeof AppSaudeWarmupIdRoute
  '/_app/saude/tom': typeof AppSaudeTomRoute
  '/diario/exercicio/$exerciseId': typeof DiarioExercicioExerciseIdRoute
  '/repertorio/imprimir/$projectId': typeof RepertorioImprimirProjectIdRoute
  '/_app/diario/': typeof AppDiarioIndexRoute
  '/_app/repertorio/': typeof AppRepertorioIndexRoute
  '/_app/saude/': typeof AppSaudeIndexRoute
  '/_app/teste-vocal/': typeof AppTesteVocalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/home'
    | '/diario/concluido'
    | '/palco/$projectId'
    | '/teste-vocal/executar'
    | '/diario/evolucao'
    | '/repertorio/$projectId'
    | '/saude/$warmupId'
    | '/saude/tom'
    | '/diario/exercicio/$exerciseId'
    | '/repertorio/imprimir/$projectId'
    | '/diario/'
    | '/repertorio/'
    | '/saude/'
    | '/teste-vocal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/home'
    | '/diario/concluido'
    | '/palco/$projectId'
    | '/teste-vocal/executar'
    | '/diario/evolucao'
    | '/repertorio/$projectId'
    | '/saude/$warmupId'
    | '/saude/tom'
    | '/diario/exercicio/$exerciseId'
    | '/repertorio/imprimir/$projectId'
    | '/diario'
    | '/repertorio'
    | '/saude'
    | '/teste-vocal'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/home'
    | '/diario/concluido'
    | '/palco/$projectId'
    | '/teste-vocal/executar'
    | '/_app/diario/evolucao'
    | '/_app/repertorio/$projectId'
    | '/_app/saude/$warmupId'
    | '/_app/saude/tom'
    | '/diario/exercicio/$exerciseId'
    | '/repertorio/imprimir/$projectId'
    | '/_app/diario/'
    | '/_app/repertorio/'
    | '/_app/saude/'
    | '/_app/teste-vocal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  DiarioConcluidoRoute: typeof DiarioConcluidoRoute
  PalcoProjectIdRoute: typeof PalcoProjectIdRoute
  TesteVocalExecutarRoute: typeof TesteVocalExecutarRoute
  DiarioExercicioExerciseIdRoute: typeof DiarioExercicioExerciseIdRoute
  RepertorioImprimirProjectIdRoute: typeof RepertorioImprimirProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teste-vocal/executar': {
      id: '/teste-vocal/executar'
      path: '/teste-vocal/executar'
      fullPath: '/teste-vocal/executar'
      preLoaderRoute: typeof TesteVocalExecutarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palco/$projectId': {
      id: '/palco/$projectId'
      path: '/palco/$projectId'
      fullPath: '/palco/$projectId'
      preLoaderRoute: typeof PalcoProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diario/concluido': {
      id: '/diario/concluido'
      path: '/diario/concluido'
      fullPath: '/diario/concluido'
      preLoaderRoute: typeof DiarioConcluidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teste-vocal/': {
      id: '/_app/teste-vocal/'
      path: '/teste-vocal'
      fullPath: '/teste-vocal/'
      preLoaderRoute: typeof AppTesteVocalIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saude/': {
      id: '/_app/saude/'
      path: '/saude'
      fullPath: '/saude/'
      preLoaderRoute: typeof AppSaudeIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repertorio/': {
      id: '/_app/repertorio/'
      path: '/repertorio'
      fullPath: '/repertorio/'
      preLoaderRoute: typeof AppRepertorioIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diario/': {
      id: '/_app/diario/'
      path: '/diario'
      fullPath: '/diario/'
      preLoaderRoute: typeof AppDiarioIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/repertorio/imprimir/$projectId': {
      id: '/repertorio/imprimir/$projectId'
      path: '/repertorio/imprimir/$projectId'
      fullPath: '/repertorio/imprimir/$projectId'
      preLoaderRoute: typeof RepertorioImprimirProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diario/exercicio/$exerciseId': {
      id: '/diario/exercicio/$exerciseId'
      path: '/diario/exercicio/$exerciseId'
      fullPath: '/diario/exercicio/$exerciseId'
      preLoaderRoute: typeof DiarioExercicioExerciseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/saude/tom': {
      id: '/_app/saude/tom'
      path: '/saude/tom'
      fullPath: '/saude/tom'
      preLoaderRoute: typeof AppSaudeTomRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saude/$warmupId': {
      id: '/_app/saude/$warmupId'
      path: '/saude/$warmupId'
      fullPath: '/saude/$warmupId'
      preLoaderRoute: typeof AppSaudeWarmupIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repertorio/$projectId': {
      id: '/_app/repertorio/$projectId'
      path: '/repertorio/$projectId'
      fullPath: '/repertorio/$projectId'
      preLoaderRoute: typeof AppRepertorioProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diario/evolucao': {
      id: '/_app/diario/evolucao'
      path: '/diario/evolucao'
      fullPath: '/diario/evolucao'
      preLoaderRoute: typeof AppDiarioEvolucaoRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppHomeRoute: typeof AppHomeRoute
  AppDiarioEvolucaoRoute: typeof AppDiarioEvolucaoRoute
  AppRepertorioProjectIdRoute: typeof AppRepertorioProjectIdRoute
  AppSaudeWarmupIdRoute: typeof AppSaudeWarmupIdRoute
  AppSaudeTomRoute: typeof AppSaudeTomRoute
  AppDiarioIndexRoute: typeof AppDiarioIndexRoute
  AppRepertorioIndexRoute: typeof AppRepertorioIndexRoute
  AppSaudeIndexRoute: typeof AppSaudeIndexRoute
  AppTesteVocalIndexRoute: typeof AppTesteVocalIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHomeRoute: AppHomeRoute,
  AppDiarioEvolucaoRoute: AppDiarioEvolucaoRoute,
  AppRepertorioProjectIdRoute: AppRepertorioProjectIdRoute,
  AppSaudeWarmupIdRoute: AppSaudeWarmupIdRoute,
  AppSaudeTomRoute: AppSaudeTomRoute,
  AppDiarioIndexRoute: AppDiarioIndexRoute,
  AppRepertorioIndexRoute: AppRepertorioIndexRoute,
  AppSaudeIndexRoute: AppSaudeIndexRoute,
  AppTesteVocalIndexRoute: AppTesteVocalIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  DiarioConcluidoRoute: DiarioConcluidoRoute,
  PalcoProjectIdRoute: PalcoProjectIdRoute,
  TesteVocalExecutarRoute: TesteVocalExecutarRoute,
  DiarioExercicioExerciseIdRoute: DiarioExercicioExerciseIdRoute,
  RepertorioImprimirProjectIdRoute: RepertorioImprimirProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
